apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: graviton-testing
  region: us-west-2
  version: "1.19"
nodeGroups:
  - name: graviton
    instanceType: t4g.medium
    desiredCapacity: 2
    volumeSize: 10
    ssh:
      allow: false
  - name: t3
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 10
    ssh:
      allow: false
