apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 8
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample-app
        image: ctrahey/hello-arch:latest
        ports:
        - name: http
          containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
spec:
  type: LoadBalancer
  selector:
    app: sample
  ports:
  - name: http
    port: 80
    targetPort: http

    